[build]
 command = "bundle exec jekyll build"
 publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"
  # Bundler version comes from Gemfile.lock (BUNDLED WITH 2.4.22)
